### ISSUE TITLE
Thoughts on adding a few utility methods?

### ISSUE THREAD

**Issue by ghost** [equip/structure#2]
Just curious if you've considered adding map($callback) and filter($callback) methods to the collections as I find myself wishing these existed quite often.  These would be value operations and wouldn't affect dictionary keys (though I suppose there may be uses for mapping/filtering keys, I haven't run into a use case yet).  Would be happy to implement and submit a pull request if you feel they could be worthwhile additions.

Thoughts?

**Comment by shadowhand** [comment]
Have you tried [Knapsack](https://github.com/DusanKasan/Knapsack)?

**Comment by ghost** [comment]
No, first time I've heard of it.  Looks very interesting...I suppose no real reason to add map/filter functionality when there's another lib that provides it already (because this isn't Javascript, amirite...)

Thanks for the quick response!

**Comment by shadowhand** [comment]
Knapsack *should* work just fine with this package, since it operates on anything that is `Traversable`. Let us know if it doesn't work for you!
